### PR TITLE
refactor: use InvokeFunction from transaction_request.rs

### LINKED ISSUE #88: Duplicate InvokeFunction types
Looks like `starknet_core::types::transaction_request::InvokeFunctionTransaction` is literally the same as  `starknet_core::types::call_contract::CallContractResult`. We should remove the latter.

### PR DESCRIPTION
**Pull request by milancermak**
Resolves #88, probably :)

### CODE REVIEW

**Review by xJonathanLEI — CHANGES_REQUESTED** [review]
All good except it now clashes with #87 lol.

Please rebase :)

**Comment by milancermak** [comment]
this :)

**Comment by xJonathanLEI** [comment]
Wow GitHub has this little file explorer thingy on the side:

image

like... finally.

**Review by xJonathanLEI — APPROVED** [review]
👍

**Pull request merged**
