### PR TITLE
feat: add WebAssembly support

### LINKED ISSUE #78: WebAssembly support
Currently `cargo build --target wasm32-unknown-unknown` fails on the repo. This issue tracks the progress of making `starknet-rs` work in WebAssembly.

### PR DESCRIPTION
**Pull request by xJonathanLEI**
Resolves #78.

This PR:

- resolves a few issues that were causing `wasm32` builds to fail:
  - `js` feature in `getrandom` needed for WASM to work;
  - `bitvec` not behaving well in `wasm32` (this PR removes `bitvec` for good);
  - `crypto-bigint` uses `u32` in 32-bit mode while `ark-ff` doesn't care.
- adds an example for using `starknet-rs` in browser with WebPack.

You can now use `starknet-rs` in browser :)

### CODE REVIEW

**Comment by milancermak** [comment]
Should we add support for wasm32 into the CI?

**Review by milancermak — APPROVED** [review]
LGTM.

I couldn't actually get the JS in index.html working because of some browser BS and I didn't want to spend more time on resolving it. Doesn't matter, ship it.

**Comment by xJonathanLEI** [comment]
Did you run `yarn build` before serving the page though?

**Comment by milancermak** [comment]
Yes, I did. How do you serve it then?

**Comment by xJonathanLEI** [comment]
```bash
$ yarn global add serve
$ serve -p 3000 -s dist/
```

**Comment by milancermak** [comment]
Cool, that works!

**Pull request merged**
