### PR TITLE
test: make hardcoded RPC address configurable

### LINKED ISSUE #462: Make hardcoded RPC address configurable
We want to incorporate starknet-rs test in our CI.
Making the rpc address to be overridable by an env variable would be really helpful.

https://github.com/NethermindEth/juno/issues/1114

### PR DESCRIPTION
**Pull request by omerfirmak**
Fixes #462

### CODE REVIEW

**Comment by xJonathanLEI** [comment]
CI red. Mind fixing?

**Comment by omerfirmak** [comment]
Fixed formatting, I think some tests are flakey tho.

**Comment by xJonathanLEI** [comment]
Don't worry about that part. It seems to be a pathfinder issue. I will retry if they fail.

BTW some tests are marked as `ignore` due to pathfinder bugs (fixed in 0.7.2 but I'm still running 0.7.1 as of now). If you want to run all tests you need to do something like `cargo test --all -- --include-ignored`.

**Comment by omerfirmak** [comment]
> `cargo test --all -- --include-ignored`

Nice, good to know. Thanks!

**Pull request merged**
