### PR TITLE
feat(starknet-accounts): Estimate Fee for Account

### PR DESCRIPTION
**Pull request by abigger87**
Exposes a fee estimation function from within the `starknet-accounts/src/account.rs` `Account` trait.

This follows starknet.js' convention defined [here](https://github.com/0xs34n/starknet.js/blob/develop/src/account/default.ts#L49).

### CODE REVIEW

**Comment by xJonathanLEI** [comment]
Hey thanks for the PR but the CI is failing. Could you please resolve?

**Comment by abigger87** [comment]
> Hey thanks for the PR but the CI is failing. Could you please resolve?

Fixed :)

**Comment by exp-table** [comment]
:point_right::point_left: Could y'all merge this?

**Comment by xJonathanLEI** [comment]
Sorry for not reviewing this PR in time, but since this very same functionality has been implemented in #115, I'm closing this one here.

**Pull request closed without merging**
