### PR TITLE
feat: add `abigen!` macro

### LINKED ISSUE #286: Parsing a `FunctionCall` call return variable of type`Vec<FieldElement>` using a contract's ABI
Hey:), 

I'm currently using `starknet-rs` to call the [Kakarot contract](https://github.com/sayajin-labs/kakarot). Specifically, its entrypoint named `execute_at_address` (although it is an external function, I call it here as a view).

Here is the signature of the function:
```cairo
func execute_at_address{
    syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr, bitwise_ptr: BitwiseBuiltin*
}(address: felt, value: felt, gas_limit: felt, calldata_len: felt, calldata: felt*) -> (
    stack_accesses_len: felt,
    stack_accesses: felt*,
    stack_len: felt,
    memory_accesses_len: felt,
    memory_accesses: felt*,
    memory_bytes_len: felt,
    evm_contract_address: felt,
    starknet_contract_address: felt,
    return_data_len: felt,
    return_data: felt*,
)
```

I manage to call this function fine, and the return is:
```
0x000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006661abd0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000090000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000abde1007e67126e0755af0ff0173f919738f8373062897a9e931ba1ae4721548bd963e3fe67126e0755af0ff0173f919738f8373000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002
```
I'd like to isolate each variable in the return. Is there an easy way to do it with Starknet-rs? If not, I can help in building a method to accomplish that.

Thanks! Have a good one

### LINKED ISSUE #445: [feat] Add contract types like in other SDKs
In starknet-py or starknet-js, one can use the `Contract` class, especially `Contract.from_address` to have a high level human-readable interaction with contracts. For example, one can do

```
starknet_eth = Contract.from_address(provider, 0x49...)
await starknet_eth.balance_of(0x1234)
```

or also build such an object from an embedded abi object.

Currently with starknet-rs, we end up doing encoding and decoding manually with raw starknet call/invoke. Or I am missing something?

### PR DESCRIPTION
**Pull request by glihm**
Here is the first draft for `abigen!` macro.

# Issues
fixes #286
fixes #445 

# Usage
This macro aims at being used like:

```rust
// From a abi json file (path relative to Cargo.toml file).
abigen!(ContractName, "/path/abi.json");

// From a literal string containing the JSON. This one was more used for
// testing, perhaps not useful.
abigen!(ContractName, r#"
[{...}]
"#);
```

# Code organization
The code is separated in 3 parts:

1. `cairo_types` which contains the mapping of Cairo native types into rust types.
2. `parser` contains all the logic to parse ABI as a JSON, where types are strings, and totally flatten. This is where the generic types are detected and applied to each member/variant or struct/enum.
3. `abigen` contains the code logic related to macro expansion and code generation.

# Examples
Two examples were added:

1. `abigen.rs` contains the very basic usage working on testnet with user addresses.
2. `abigen_event.rs` shows how `abigen!` facilitate the deserialization of events.

### CODE REVIEW

**Comment by glihm** [comment]
Just seen that `ConnectedAccount` trait offers a method to get the provider from the account.

Maybe we want two ways of initialize the contract:

```rust
// For calls only.
let contract = MyContract::new(address, provider);

// For invoke and calls.
let contract = MyContract::new_with_account(address, account);
```

And internally, we use the provider if present in case 1, or the one from the account in case 2.
Perhaps this will be easier for init. To be checked with Pia (can't tag here right now) as she working on the `with_account` design.

**Comment by glihm** [comment]
@xJonathanLEI let me know when you would have time for a first review, in order to keep going forward with this feature. :+1:

I am testing a new version where every interface in the ABI is implemented in a trait, this IMO can be helpful to easily switch targeted contracts without changing the actual code using them.

**Comment by glihm** [comment]
Other idea that may be interesting, we can add some option for the code generation. For instance, it can be useful sometimes to get access to the `Call` generated by an external, without sending the transaction. This can help when we only want to send one transaction, with several calls inside it.

**Comment by Eikix** [comment]
Hey:)! At Kakarot, we're super interested in such a feature, any ETA or reason why it shouldn't more forward for now?

**Comment by glihm** [comment]
> Hey:)! At Kakarot, we're super interested in such a feature, any ETA or reason why it shouldn't more forward for now?

Hey! Currently re-working the code to enhance the proposition in this PR using Syn crate to parse types and enhancing devX following alloy nomenclature.

This will allow more flexibility on configuration for the calls and invokes.

**Pull request closed without merging**
