### PR TITLE
feat(starknet-providers): Make Provider Futures Send

### PR DESCRIPTION
**Pull request by abigger87**
Changes the `#[async_trait(?Send)]` attribute to `#[async_trait]`

### CODE REVIEW

**Comment by xJonathanLEI** [comment]
Hi thanks for the PR. Could you explain the rationale for this change? I believe it was added to make WASM work.

Also it looks like our there's something wrong with our GitHub Actions settings. CI seems to not be running.

**Comment by xJonathanLEI** [comment]
Maybe related?

https://www.githubstatus.com/incidents/y5hdmv0p49x3

Let me try closing and re-opening the PR to see of it can be triggered successfully. Sorry for the notification spam.

**Comment by xJonathanLEI** [comment]
OK it _is_ related.

**Comment by abigger87** [comment]
No worries - the reason I wanted to open this is to be able to send the provider futures across runtime threads!

**Comment by xJonathanLEI** [comment]
It looks like our current CI pipeline doesn't attempt to build the whole project for WASM... it's not catching the build failure as a result.

I just tried running `cargo build --target wasm32-unknown-unknown` on your branch and it fails.

**Comment by xJonathanLEI** [comment]
I just updated our CI workflow to include building for wasm, but I think this PR is still running the old version. That's why it's all green. Actually your branch fails the wasm build.

Might need to use conditional attribute instead?

**Pull request closed without merging**
